services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: sh -c "npm install && npm start"

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sprint3
    ports:
      - "3306:3306"
    volumes:
      - ./sd2-db.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"   # ← use 8080
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db