CREATE DATABASE IF NOT EXISTS sprint3;
USE sprint3;

CREATE TABLE users (
 id INT AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(50),
 email VARCHAR(100),
 password VARCHAR(255)
);

CREATE TABLE posts (
 id INT AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(255),
 content TEXT,
 user_id INT
);

CREATE TABLE tags (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(50)
);

CREATE TABLE post_tags (
 post_id INT,
 tag_id INT
);